config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :categories
  resources :ai_products
  get "search", to: "ai_products#search"
  get  'inquiry' => 'inquiry#index'            
  post 'inquiry/confirm' => 'inquiry#confirm'   
  post 'inquiry/thanks' => 'inquiry#thanks' 
end

app/models/ai_product.rb
class AiProduct < ApplicationRecord
  has_many :ai_products_purposes
  has_many :purposes, through: :ai_products_purposes

  has_many :ai_products_target_companies
  has_many :target_companies,through: :ai_products_target_companies

  has_many :ai_products_target_industries
  has_many :target_industries, through: :ai_products_target_industries

  has_many :chat_gpt_products_introductions
  
  has_many :ai_products_categories
  has_many :categories, through: :ai_products_categories

  has_one :chat_gpt_ai_products_introduction
  def image_path
    ActionController::Base.helpers.asset_path(image)
  end
end

app/controllers/ai_products_controller.rb
class AiProductsController < ApplicationController
  def index
    @ai_products = AiProduct.joins(:categories, :purposes, :chat_gpt_ai_products_introduction).order('RANDOM()').page(params[:page]).per(9)
    @categories = Category.all
    @purposes = Purpose.all
  end

  def show
    @ai_product = AiProduct.joins(:chat_gpt_ai_products_introduction).find(params[:id])

    formatted_faqs = @ai_product.faq.gsub("[", "").gsub("]", "").gsub('"', "").gsub('\n', "").gsub(',', "")
    segments = formatted_faqs.split(/([？。])/).each_slice(2).map(&:join)

    qa_pairs = []
    question = nil

    segments.each do |segment|
      if segment.end_with?("？")
        question = segment.strip
      elsif segment.end_with?("。") && question
        qa_pairs << [question, segment.strip]
        question = nil
      end
    end

    # @qa_pairsにセット
    @qa_pairs = qa_pairs
  end

  def search
    search_word = params[:search]
    category_ids = params[:category] || []
    purpose_ids = params[:purpose] || []

    @categories = Category.all
    @purposes = Purpose.all
    @ai_products = AiProduct.all.page(params[:page]).per(9)
    # @ai_products = @ai_products.where('product_name LIKE ?', "%#{search_word}%")

    if search_word.present?
      @ai_products = @ai_products.where('product_name LIKE ?', "%#{search_word}%")
    end

    if category_ids.any?
      @ai_products = @ai_products.joins(:categories).where(categories: { id: category_ids }).distinct
    end

    if purpose_ids.any?
      @ai_products = @ai_products.joins(:purposes).where(purposes: { id: purpose_ids }).distinct
    end

    respond_to do |format|
      format.html { render :index }
      format.js   { render partial: 'index' }
    end
  end

  # def self.search_for(content, method)
  #   AiProduct.where('name LIKE ?', '%' + content)
  # end

end

app/helpers/ai_products_helper.rb
module AiProductsHelper
end

app/views/ai_products/_index_content.html.erb
<div class="products">
  <% @ai_products.each do |ai_product| %>
  <div class="product-item">
    <div class="product-header">
      <h3 class="product-name"><%= ai_product.product_name %></h3>
      <input type="checkbox" name="compare" class="compare-checkbox">
    </div>
    <p class="product-summary"><%= ai_product.description %></p>
    <p class="product-rating">
      <i class="fas fa-star text-orange-500"></i> <%= ai_product.rating %> (200 reviews)
    </p>
    <%= link_to '製品詳細', ai_product_path(ai_product), class: 'details-button' %>
  </div>
  <% end %>
</div>

app/views/ai_products/index.html.erb
<div class = "search_products_container">
  <aside class="sidebar">
    <h2>フィルターオプション</h2>
    <%= form_with url: search_path, method: :get, remote: true do |f| %>
      <div class="filter-group">
        <label for="search">AIツールを検索:</label>
        <%= f.text_field :search, placeholder: "AIツールを検索", class: "search-input" %>
      </div>
      <div class="filter-group">
        <label>カテゴリ:</label>
        <span id="toggle-category-list" class="toggle-button">カテゴリを表示</span>
        <div id="category-list" class="category-list">
          <% @categories.each_with_index do |category, index| %>
            <div class="filter-option">
              <%= check_box_tag 'category[]', category.id, false, id: "category_#{category.id}" %>
              <%= label_tag "category_#{category.id}", category.category %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="filter-group">
        <label>利用目的:</label>
        <span id="toggle-purpose-list" class="toggle-button">利用目的一覧を表示</span>
        <div id="purpose-list" class="category-list">
          <% @purposes.each_with_index do |purpose, index| %>
            <div class="filter-option">
              <%= check_box_tag 'purpose[]', purpose.id, false, id: "purpose_#{purpose.id}" %>
              <%= label_tag "purpose_#{purpose.id}", purpose.purpose %>
            </div>
          <% end %>
        </div>
      </div>
    <%= f.submit "フィルター", class: "filter-button" %>
    <% end %>
  </aside>

  <section class="product-list" id="ai_products">
    <div class="search_products">
      <!-- AI製品の例 -->
      <% @ai_products.each do |ai_product| %>
      <div class="product-item">
        <div class="product-header">
          <h3 class="product-name"><%= ai_product.product_name %></h3>
        </div>
        <p class="product-summary"><%= ai_product.chat_gpt_ai_products_introduction.introduction %></p>
        <p class="product-fee-type badge badge-secondary">
          <%= ai_product.usage_fee_type %>
        </p>
        <% ai_product.categories.each do |category| %>
          <span class="badge badge-secondary"><%= category.category %></span>
        <% end %>
         <%= link_to '製品詳細', ai_product_path(ai_product), class: 'details-button' %>
      </div>
      <% end %>
    </div>
    <%= paginate @ai_products %>
  </section>
 </div> 

app/views/ai_products/search.js.erb
$('#ai_products').html("<%= j render 'index' %>");

app/views/ai_products/show.html.erb
<section class="container-fluid my-4">
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @ai_product.image, alt: "製品画像", class: "img-fluid" %>
    </div>
    <div class="col-md-6">
      <div class="aiproduct-wrapper">
        <h1 class="heading"><%= @ai_product.product_name %></h1>
        <p class="description"><%= @ai_product.chat_gpt_ai_products_introduction.introduction %></p>
      </div>
    </div>
  </div>
</section>
  <div class="mt-5">
    <h2 class="">運営企業情報</h2>
      <ul class="list-group">
        <li class="list-group-item">企業名：<%= @ai_product.company_name %></li>
        <li class="list-group-item">資本金：<%= @ai_product.capital %></li>
        <li class="list-group-item">事業内容：<%= @ai_product.business_description %></li>
      </ul>
  </div>
  <div class="">
    <table class="table mt-5">
      <thead>
        <tr>
          <th scope="col">無料トライアル</th>
          <th scope="col">利用料金</th>
          <th scope="col">初期費用</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <% if @ai_product.trial == true %>
              無料トライアルあり
            <% elsif @ai_product.trial == false %>
              無料試用なし
            <% else %>
              お問い合わせください。
            <% end %>
          </td>
          <td><%= @ai_product.usag_fee_scrape %></td>
          <td>
            <% if @ai_product.initial_cost.present? %>
              <%= @ai_product.initial_cost %>
            <% else%>
              お問い合わせください。
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
    <div class="mt-5">
      <h2 class="">よくある質問</h2>
        <ul class="list-group">
          <% @qa_pairs.each_with_index do |pair, index| %>
            <% unless pair[0].nil? || pair[0].strip.empty? || pair[1].nil? || pair[1].strip.empty? %>
              <li class="list-group-item">
                <strong>質問:</strong> <%= pair[0] %><br>
                <strong>回答:</strong> <%= pair[1] %>
              </li>
            <% end %>
          <% end %>
        </ul>
    </div>