config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :categories
  resources :ai_products
  get "search", to: "ai_products#search"
  get  'inquiry' => 'inquiry#index'            
  post 'inquiry/confirm' => 'inquiry#confirm'   
  post 'inquiry/thanks' => 'inquiry#thanks' 
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ai_products_categories
  has_many :ai_products, through: :ai_products_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all

  end

  def show
    @category = Category.find(params[:id])
    @ai_products = AiProduct.joins(:categories).where(categories: { id: @category.id }).page(params[:page]).per(9)
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<section class="categories">
  <h2>カテゴリ一覧</h2>
  <ul>
    <% @categories.each do |category| %>
    <li><%= link_to category.category, category_path(category)%></li>
    <% end %>
  </ul>
</section>

app/views/categories/show.html.erb
<section class="product-list" id="ai_products">
    <div class="search_products">
      <!-- AI製品の例 -->
      <% @ai_products.each do |ai_product| %>
      <div class="product-item">
        <div class="product-header">
          <h3 class="product-name"><%= ai_product.product_name %></h3>
        </div>
        <p class="product-summary"><%= ai_product.description %></p>
        <p class="product-rating">
          <i class="fas fa-star text-orange-500"></i> 4.5 (200 reviews)
        </p>
        <% ai_product.categories.each do |category| %>
          <span class="badge badge-secondary"><%= category.category %></span>
        <% end %>
         <%= link_to '製品詳細', ai_product_path(ai_product), class: 'details-button' %>
      </div>
      <% end %>
    </div>
    <%= paginate @ai_products %>
  </section>