config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :categories
  resources :ai_products
  get "search", to: "ai_products#search"
  get  'inquiry' => 'inquiry#index'            
  post 'inquiry/confirm' => 'inquiry#confirm'   
  post 'inquiry/thanks' => 'inquiry#thanks' 
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-container">
  <%= link_to root_path,class:"no-underline" do %>
    <div class="footer-logo">
      <h1 class="footer-logo-title"><span class="logo-description">あらゆるAIツールを一目で比較・検討</span>AI-Syllabus</h1>
    </div>
  <% end %>
    <h3>ニュースレター登録</h3>
  <form>
    <input type="email" name="email" placeholder="メールアドレス">
    <button type="submit">登録</button>
  </form>
    <div class="footer-nav-container">
      <div class="footer-nav">
        <ul class="nav-list">
          <li class="nav-list-item">
            <%= link_to 'ホーム', root_path %>
          </li>
          </li>
          <li class="nav-list-item">
            <%= link_to 'カテゴリ一覧', categories_path %>
          </li>
        </ul>
      </div>
    </div>
    <div class="copy-right">
      <small>Copyright © 2024 AI-Syllabus inc. All Rights Reserved.</small>
    <div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="pc-nav">
    <ul>
        <li style="width:113px; text-align:center;"><%= link_to "トップページ", root_path, class: "nav-link"%></li>
        <li style="width:113px; text-align:center;"><%= link_to "製品検索", ai_products_path, class: "nav-link"%></li>
        <li style="width:113px; text-align:center;"><%= link_to "カテゴリ一覧", categories_path, class: "nav-link"%></li>
        <li style="width:113px; text-align:center;"><%= link_to "お問い合わせ", inquiry_path, class: "nav-link"%></li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!-- Bootstrap Javascript(jQuery含む) -->

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI-Syllabus</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <script src="https://kit.fontawesome.com/577b664e94.js" crossorigin="anonymous"></script>
</head>
  <body>
    <header>
      <%= render 'layouts/nav' %>
    </header>
    <main>
      <%= yield %>
    </main>
    <%= javascript_include_tag 'application' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <footer>
    <%= render 'layouts/footer'%>
    </footer>
  </body>
</html>